#!/bin/bash
# build-static-script.sh — Build a single-file Jerboa script as a static Linux binary
#
# Usage (inside jerboa21/jerboa Docker container):
#   build-static-script.sh <script.ss> <output-name>
#
# The script compiles <script.ss> with Whole-Program Optimization, embeds
# Chez boot files + the compiled program as C arrays, then links a fully
# static x86_64 binary against the musl Chez kernel and libjerboa_native.a.
#
# Environment variables (all have sane defaults inside the Docker image):
#   JERBOA_HOME              — path to jerboa repo (default: /build/mine/jerboa)
#   JERBOA_MUSL_CHEZ_PREFIX  — musl Chez install prefix (default: /build/chez-musl)
#
# Output: ./<output-name>  (statically linked ELF, target <25 MB)
#
# See ~/mine/jerboa/docs/single-binary.md for architecture details.

set -euo pipefail

SCRIPT="${1:?Usage: build-static-script.sh <script.ss> <output-name>}"
OUTPUT="${2:?Usage: build-static-script.sh <script.ss> <output-name>}"

JERBOA_HOME="${JERBOA_HOME:-/build/mine/jerboa}"
MUSL_CHEZ="${JERBOA_MUSL_CHEZ_PREFIX:-/build/chez-musl}"
NATIVE_A="${JERBOA_HOME}/jerboa-native-rs/target/x86_64-unknown-linux-musl/release/libjerboa_native.a"
LIBDIRS="${JERBOA_HOME}/lib"
SCHEME="${SCHEME:-scheme}"

echo "=== Jerboa static build: ${SCRIPT} → ${OUTPUT} ==="
echo "    JERBOA_HOME = ${JERBOA_HOME}"
echo "    MUSL_CHEZ   = ${MUSL_CHEZ}"
echo ""

# ── Locate musl Chez libkernel.a ─────────────────────────────────────────────
MACHINE_TYPE=$(${SCHEME} -q <<'EOF'
(display (machine-type)) (exit)
EOF
)

CSV_DIR=""
for d in "${MUSL_CHEZ}/lib/csv"*/"${MACHINE_TYPE}"; do
    if [ -f "${d}/libkernel.a" ]; then
        CSV_DIR="${d}"
        break
    fi
done

if [ -z "${CSV_DIR}" ] || [ ! -f "${CSV_DIR}/libkernel.a" ]; then
    echo "ERROR: Cannot find musl libkernel.a under ${MUSL_CHEZ}/lib/csv*/${MACHINE_TYPE}" >&2
    echo "  machine-type reported: ${MACHINE_TYPE}" >&2
    exit 1
fi

echo "  Chez:   ${CSV_DIR}"
echo "  Native: ${NATIVE_A}"
echo ""

if [ ! -f "${NATIVE_A}" ]; then
    echo "ERROR: ${NATIVE_A} not found" >&2
    echo "  Run: cd ${JERBOA_HOME}/jerboa-native-rs && cargo build --release --target x86_64-unknown-linux-musl --no-default-features" >&2
    exit 1
fi

# ── Step 1: Compile script with WPO → <output>.wp.so ─────────────────────────
WPO_SO="${OUTPUT}.wp.so"
# Writable dir for compiled library .so output (source lib dir may be read-only)
OBJ_DIR="/tmp/jerboa-obj-$$"
mkdir -p "${OBJ_DIR}"
echo "==> Step 1: Compile ${SCRIPT} with WPO → ${WPO_SO}"
echo "    Library object cache: ${OBJ_DIR}"

LD_LIBRARY_PATH="${JERBOA_HOME}/jerboa-native-rs/target/release:${LD_LIBRARY_PATH:-}" \
  ${SCHEME} --libdirs "${LIBDIRS}" \
    --script "${JERBOA_HOME}/support/build-boot.ss" "${SCRIPT}" "${WPO_SO}" "${OBJ_DIR}"

echo ""

# ── Step 2: Convert boot files and program .so to C byte-array headers ────────
echo "==> Step 2: Convert to C headers"

convert_to_header() {
    local input="$1"
    local stem="$2"
    local varname
    varname="$(basename "${stem}")_data"
    local sizename
    sizename="$(basename "${stem}")_size"
    local header="${stem}.h"

    echo "  ${input} → ${header}"
    printf "static const unsigned char %s[] = {\n" "${varname}" > "${header}"
    od -An -tx1 -v "${input}" \
        | sed 's/^ *//;s/ *$//;s/  */ /g;s/ /,0x/g;s/^/0x/;s/$/,/' >> "${header}"
    printf "};\n" >> "${header}"
    printf "static const unsigned int %s = sizeof(%s);\n" \
        "${sizename}" "${varname}" >> "${header}"
}

convert_to_header "${CSV_DIR}/petite.boot" "petite_boot"
convert_to_header "${CSV_DIR}/scheme.boot" "scheme_boot"
convert_to_header "${WPO_SO}"             "program_boot"

echo ""

# ── Step 3: Generate C main ───────────────────────────────────────────────────
echo "==> Step 3: Generate ${OUTPUT}-main.c"

cat > "${OUTPUT}-main.c" << 'CMAIN'
/*
 * Jerboa static binary entry point — generated by build-static-script.sh
 *
 * Embeds petite.boot, scheme.boot, and the compiled program (.so) as
 * static byte arrays.  Registers all Jerboa native + POSIX FFI symbols
 * so foreign-procedure works without dlopen.
 *
 * Override dlopen/dlsym/dlclose/dlerror with stubs: every Jerboa stdlib
 * module wraps load-shared-object in (guard ...) so they degrade cleanly.
 * The actual symbol resolution happens via Sforeign_symbol below.
 */

#include "scheme.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <sys/stat.h>
#include <signal.h>
#include <pthread.h>
#include <time.h>
#include <errno.h>
#include <sys/mman.h>
#include <sys/wait.h>

/* Embedded boot data — generated by build-static-script.sh */
#include "petite_boot.h"
#include "scheme_boot.h"
#include "program_boot.h"

/* ── dlopen stubs ─────────────────────────────────────────────────────────── */
/* musl static does not support dlopen; stub it out so (load-shared-object ...)
 * in stdlib modules does not crash.  All real symbol resolution uses
 * Sforeign_symbol registered in custom_init() below. */
static int _static_dummy;
void  *dlopen (const char *p, int m) { (void)p; (void)m; return &_static_dummy; }
void  *dlsym  (void *h, const char *n) { (void)h; (void)n; return NULL; }
int    dlclose(void *h) { (void)h; return 0; }
char  *dlerror(void)    { return NULL; }

/* ── GCC 13 / musl compatibility stub ────────────────────────────────────── */
/* GCC 13's libgcc_eh.a references _dl_find_object (glibc 2.35+) which musl
 * does not provide.  Return -1 (not found) — safe because Chez uses its own
 * continuation/exception machinery, not libgcc unwinding. */
int _dl_find_object(void *addr, void *result) { (void)addr; (void)result; return -1; }

/* htons/ntohs may be macros — wrap for Sforeign_symbol */
static unsigned short wrap_htons(unsigned short x) { return htons(x); }
static unsigned short wrap_ntohs(unsigned short x) { return ntohs(x); }
static unsigned long  wrap_htonl(unsigned long  x) { return htonl(x); }
static unsigned long  wrap_ntohl(unsigned long  x) { return ntohl(x); }

/* ── FFI registration ─────────────────────────────────────────────────────── */
/* Called by Sbuild_heap before Scheme code runs.
 * Register every symbol that any imported library calls via foreign-procedure. */

/* Declare all jerboa_* symbols from libjerboa_native.a */
/* TLS */
extern unsigned long long jerboa_tls_server_new(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_tls_server_new_mtls(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_tls_server_new_pem(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_tls_server_new_mtls_pem(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern void  jerboa_tls_server_free(unsigned long long);
extern unsigned long long jerboa_tls_accept(unsigned long long,int);
extern unsigned long long jerboa_tls_connect(unsigned char*,unsigned long long,unsigned short);
extern unsigned long long jerboa_tls_connect_pinned(unsigned char*,unsigned long long,unsigned short,unsigned char*,unsigned long long);
extern unsigned long long jerboa_tls_connect_mtls(unsigned char*,unsigned long long,unsigned short,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_tls_read(unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_tls_write(unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_tls_flush(unsigned long long);
extern void   jerboa_tls_close(unsigned long long);
extern int    jerboa_tls_set_nonblock(unsigned long long,int);
extern int    jerboa_tls_get_fd(unsigned long long);
extern unsigned long long jerboa_last_error(unsigned char*,unsigned long long);
/* Crypto — correct names (not jerboa_sha/hmac/argon/pbkdf/chacha/md) */
extern int    jerboa_sha1(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_sha256(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_sha384(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_sha512(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_hmac_sha256(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_hmac_sha256_verify(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_hkdf_sha256(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_md5(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_random_bytes(unsigned char*,unsigned long long);
extern unsigned long long jerboa_aead_seal(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_aead_open(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_chacha20_seal(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_chacha20_open(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_argon2id_hash(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned long long,unsigned long long,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_argon2id_verify(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_pbkdf2_derive(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_pbkdf2_verify(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_scrypt(unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned long long,unsigned long long,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_timing_safe_equal(unsigned char*,unsigned char*,unsigned long long);
/* SQLite */
extern int    jerboa_sqlite_open(unsigned char*,unsigned long long,int);
extern int    jerboa_sqlite_exec(int,unsigned char*,unsigned long long);
extern int    jerboa_sqlite_prepare(int,unsigned char*,unsigned long long);
extern int    jerboa_sqlite_step(int);
extern int    jerboa_sqlite_finalize(int);
extern int    jerboa_sqlite_reset(int);
extern int    jerboa_sqlite_column_count(int);
extern int    jerboa_sqlite_column_type(int,int);
extern unsigned char* jerboa_sqlite_column_name(int,int);
extern unsigned char* jerboa_sqlite_column_text(int,int);
extern long long jerboa_sqlite_column_int(int,int);
extern double jerboa_sqlite_column_double(int,int);
extern unsigned char* jerboa_sqlite_column_blob(int,int);
extern int    jerboa_sqlite_bind_text(int,int,unsigned char*,unsigned long long);
extern int    jerboa_sqlite_bind_int(int,int,long long);
extern int    jerboa_sqlite_bind_double(int,int,double);
extern int    jerboa_sqlite_bind_null(int,int);
extern int    jerboa_sqlite_bind_blob(int,int,unsigned char*,unsigned long long);
extern int    jerboa_sqlite_close(int);
extern unsigned char* jerboa_sqlite_errmsg(int);
extern int    jerboa_sqlite_changes(int);
extern long long jerboa_sqlite_last_insert_rowid(int);
/* Regex */
extern int    jerboa_regex_compile(unsigned char*,unsigned long long);
extern int    jerboa_regex_compile_ex(unsigned char*,unsigned long long,int);
extern void   jerboa_regex_free(int);
extern int    jerboa_regex_is_match(int,unsigned char*,unsigned long long);
extern int    jerboa_regex_find(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_regex_find_at(int,unsigned char*,unsigned long long,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_regex_captures(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern int    jerboa_regex_group_count(int);
extern unsigned long long jerboa_regex_replace_all(int,unsigned char*,unsigned long long,unsigned char*,unsigned long long,unsigned char*,unsigned long long);
/* epoll + eventfd (all return int) */
extern int    jerboa_epoll_create(void);
extern int    jerboa_epoll_ctl(int,int,int,int);
extern int    jerboa_epoll_wait(int,unsigned char*,int,int);
extern void   jerboa_epoll_close(int);
extern int    jerboa_eventfd_create(void);
extern int    jerboa_eventfd_signal(int);
extern int    jerboa_eventfd_drain(int);
/* Compression */
extern unsigned long long jerboa_gzip(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_gunzip(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_deflate(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
extern unsigned long long jerboa_inflate(unsigned char*,unsigned long long,unsigned char*,unsigned long long);
/* Secure memory */
extern int    jerboa_secure_alloc(unsigned long long);
extern int    jerboa_secure_free(int);
extern int    jerboa_secure_random_fill(int,unsigned long long,unsigned long long);
extern int    jerboa_secure_wipe(int,unsigned long long,unsigned long long);

static void custom_init(void) {
    /* ── Jerboa native (Rust) symbols ───────────────────────────────────────── */
    Sforeign_symbol("jerboa_tls_server_new",        (void *)jerboa_tls_server_new);
    Sforeign_symbol("jerboa_tls_server_new_mtls",   (void *)jerboa_tls_server_new_mtls);
    Sforeign_symbol("jerboa_tls_server_new_pem",    (void *)jerboa_tls_server_new_pem);
    Sforeign_symbol("jerboa_tls_server_new_mtls_pem",(void*)jerboa_tls_server_new_mtls_pem);
    Sforeign_symbol("jerboa_tls_server_free",       (void *)jerboa_tls_server_free);
    Sforeign_symbol("jerboa_tls_accept",            (void *)jerboa_tls_accept);
    Sforeign_symbol("jerboa_tls_connect",           (void *)jerboa_tls_connect);
    Sforeign_symbol("jerboa_tls_connect_pinned",    (void *)jerboa_tls_connect_pinned);
    Sforeign_symbol("jerboa_tls_connect_mtls",      (void *)jerboa_tls_connect_mtls);
    Sforeign_symbol("jerboa_tls_read",              (void *)jerboa_tls_read);
    Sforeign_symbol("jerboa_tls_write",             (void *)jerboa_tls_write);
    Sforeign_symbol("jerboa_tls_flush",             (void *)jerboa_tls_flush);
    Sforeign_symbol("jerboa_tls_close",             (void *)jerboa_tls_close);
    Sforeign_symbol("jerboa_tls_set_nonblock",      (void *)jerboa_tls_set_nonblock);
    Sforeign_symbol("jerboa_tls_get_fd",            (void *)jerboa_tls_get_fd);
    Sforeign_symbol("jerboa_last_error",            (void *)jerboa_last_error);
    /* Crypto — actual symbol names from libjerboa_native.a */
    Sforeign_symbol("jerboa_sha1",                  (void *)jerboa_sha1);
    Sforeign_symbol("jerboa_sha256",                (void *)jerboa_sha256);
    Sforeign_symbol("jerboa_sha384",                (void *)jerboa_sha384);
    Sforeign_symbol("jerboa_sha512",                (void *)jerboa_sha512);
    Sforeign_symbol("jerboa_hmac_sha256",           (void *)jerboa_hmac_sha256);
    Sforeign_symbol("jerboa_hmac_sha256_verify",    (void *)jerboa_hmac_sha256_verify);
    Sforeign_symbol("jerboa_hkdf_sha256",           (void *)jerboa_hkdf_sha256);
    Sforeign_symbol("jerboa_md5",                   (void *)jerboa_md5);
    Sforeign_symbol("jerboa_random_bytes",          (void *)jerboa_random_bytes);
    Sforeign_symbol("jerboa_aead_seal",             (void *)jerboa_aead_seal);
    Sforeign_symbol("jerboa_aead_open",             (void *)jerboa_aead_open);
    Sforeign_symbol("jerboa_chacha20_seal",         (void *)jerboa_chacha20_seal);
    Sforeign_symbol("jerboa_chacha20_open",         (void *)jerboa_chacha20_open);
    Sforeign_symbol("jerboa_argon2id_hash",         (void *)jerboa_argon2id_hash);
    Sforeign_symbol("jerboa_argon2id_verify",       (void *)jerboa_argon2id_verify);
    Sforeign_symbol("jerboa_pbkdf2_derive",         (void *)jerboa_pbkdf2_derive);
    Sforeign_symbol("jerboa_pbkdf2_verify",         (void *)jerboa_pbkdf2_verify);
    Sforeign_symbol("jerboa_scrypt",                (void *)jerboa_scrypt);
    Sforeign_symbol("jerboa_timing_safe_equal",     (void *)jerboa_timing_safe_equal);
    Sforeign_symbol("jerboa_sqlite_open",           (void *)jerboa_sqlite_open);
    Sforeign_symbol("jerboa_sqlite_exec",           (void *)jerboa_sqlite_exec);
    Sforeign_symbol("jerboa_sqlite_prepare",        (void *)jerboa_sqlite_prepare);
    Sforeign_symbol("jerboa_sqlite_step",           (void *)jerboa_sqlite_step);
    Sforeign_symbol("jerboa_sqlite_finalize",       (void *)jerboa_sqlite_finalize);
    Sforeign_symbol("jerboa_sqlite_reset",          (void *)jerboa_sqlite_reset);
    Sforeign_symbol("jerboa_sqlite_column_count",   (void *)jerboa_sqlite_column_count);
    Sforeign_symbol("jerboa_sqlite_column_type",    (void *)jerboa_sqlite_column_type);
    Sforeign_symbol("jerboa_sqlite_column_name",    (void *)jerboa_sqlite_column_name);
    Sforeign_symbol("jerboa_sqlite_column_text",    (void *)jerboa_sqlite_column_text);
    Sforeign_symbol("jerboa_sqlite_column_int",     (void *)jerboa_sqlite_column_int);
    Sforeign_symbol("jerboa_sqlite_column_double",  (void *)jerboa_sqlite_column_double);
    Sforeign_symbol("jerboa_sqlite_column_blob",    (void *)jerboa_sqlite_column_blob);
    Sforeign_symbol("jerboa_sqlite_bind_text",      (void *)jerboa_sqlite_bind_text);
    Sforeign_symbol("jerboa_sqlite_bind_int",       (void *)jerboa_sqlite_bind_int);
    Sforeign_symbol("jerboa_sqlite_bind_double",    (void *)jerboa_sqlite_bind_double);
    Sforeign_symbol("jerboa_sqlite_bind_null",      (void *)jerboa_sqlite_bind_null);
    Sforeign_symbol("jerboa_sqlite_bind_blob",      (void *)jerboa_sqlite_bind_blob);
    Sforeign_symbol("jerboa_sqlite_close",          (void *)jerboa_sqlite_close);
    Sforeign_symbol("jerboa_sqlite_errmsg",         (void *)jerboa_sqlite_errmsg);
    Sforeign_symbol("jerboa_sqlite_changes",        (void *)jerboa_sqlite_changes);
    Sforeign_symbol("jerboa_sqlite_last_insert_rowid",(void*)jerboa_sqlite_last_insert_rowid);
    Sforeign_symbol("jerboa_regex_compile",         (void *)jerboa_regex_compile);
    Sforeign_symbol("jerboa_regex_compile_ex",      (void *)jerboa_regex_compile_ex);
    Sforeign_symbol("jerboa_regex_free",            (void *)jerboa_regex_free);
    Sforeign_symbol("jerboa_regex_is_match",        (void *)jerboa_regex_is_match);
    Sforeign_symbol("jerboa_regex_find",            (void *)jerboa_regex_find);
    Sforeign_symbol("jerboa_regex_find_at",         (void *)jerboa_regex_find_at);
    Sforeign_symbol("jerboa_regex_captures",        (void *)jerboa_regex_captures);
    Sforeign_symbol("jerboa_regex_group_count",     (void *)jerboa_regex_group_count);
    Sforeign_symbol("jerboa_regex_replace_all",     (void *)jerboa_regex_replace_all);
    Sforeign_symbol("jerboa_epoll_create",          (void *)jerboa_epoll_create);
    Sforeign_symbol("jerboa_epoll_ctl",             (void *)jerboa_epoll_ctl);
    Sforeign_symbol("jerboa_epoll_wait",            (void *)jerboa_epoll_wait);
    Sforeign_symbol("jerboa_epoll_close",           (void *)jerboa_epoll_close);
    Sforeign_symbol("jerboa_eventfd_create",        (void *)jerboa_eventfd_create);
    Sforeign_symbol("jerboa_eventfd_signal",        (void *)jerboa_eventfd_signal);
    Sforeign_symbol("jerboa_eventfd_drain",         (void *)jerboa_eventfd_drain);
    Sforeign_symbol("jerboa_gzip",                  (void *)jerboa_gzip);
    Sforeign_symbol("jerboa_gunzip",                (void *)jerboa_gunzip);
    Sforeign_symbol("jerboa_deflate",               (void *)jerboa_deflate);
    Sforeign_symbol("jerboa_inflate",               (void *)jerboa_inflate);
    Sforeign_symbol("jerboa_secure_alloc",          (void *)jerboa_secure_alloc);
    Sforeign_symbol("jerboa_secure_free",           (void *)jerboa_secure_free);
    Sforeign_symbol("jerboa_secure_random_fill",    (void *)jerboa_secure_random_fill);
    Sforeign_symbol("jerboa_secure_wipe",           (void *)jerboa_secure_wipe);

    /* ── POSIX / libc symbols ────────────────────────────────────────────────── */
    /* Networking (std net tcp-raw, std net fiber-httpd, std actor transport) */
    Sforeign_symbol("socket",           (void *)socket);
    Sforeign_symbol("bind",             (void *)bind);
    Sforeign_symbol("listen",           (void *)listen);
    Sforeign_symbol("accept",           (void *)accept);
    Sforeign_symbol("connect",          (void *)connect);
    Sforeign_symbol("setsockopt",       (void *)setsockopt);
    Sforeign_symbol("getsockopt",       (void *)getsockopt);
    Sforeign_symbol("getsockname",      (void *)getsockname);
    Sforeign_symbol("getpeername",      (void *)getpeername);
    Sforeign_symbol("recv",             (void *)recv);
    Sforeign_symbol("send",             (void *)send);
    Sforeign_symbol("recvfrom",         (void *)recvfrom);
    Sforeign_symbol("sendto",           (void *)sendto);
    Sforeign_symbol("shutdown",         (void *)shutdown);
    Sforeign_symbol("htons",            (void *)wrap_htons);
    Sforeign_symbol("ntohs",            (void *)wrap_ntohs);
    Sforeign_symbol("htonl",            (void *)wrap_htonl);
    Sforeign_symbol("ntohl",            (void *)wrap_ntohl);
    Sforeign_symbol("inet_pton",        (void *)inet_pton);
    Sforeign_symbol("inet_ntop",        (void *)inet_ntop);
    Sforeign_symbol("getaddrinfo",      (void *)getaddrinfo);
    Sforeign_symbol("freeaddrinfo",     (void *)freeaddrinfo);

    /* I/O */
    Sforeign_symbol("read",             (void *)read);
    Sforeign_symbol("write",            (void *)write);
    Sforeign_symbol("close",            (void *)close);
    Sforeign_symbol("open",             (void *)open);
    Sforeign_symbol("fcntl",            (void *)fcntl);
    Sforeign_symbol("dup",              (void *)dup);
    Sforeign_symbol("dup2",             (void *)dup2);
    Sforeign_symbol("pipe",             (void *)pipe);
    Sforeign_symbol("fsync",            (void *)fsync);
    Sforeign_symbol("lseek",            (void *)lseek);
    Sforeign_symbol("fstat",            (void *)fstat);
    Sforeign_symbol("stat",             (void *)stat);

    /* Process / signal (std os signal) */
    Sforeign_symbol("kill",             (void *)kill);
    Sforeign_symbol("getpid",           (void *)getpid);
    Sforeign_symbol("getppid",          (void *)getppid);
    Sforeign_symbol("fork",             (void *)fork);
    Sforeign_symbol("waitpid",          (void *)waitpid);
    Sforeign_symbol("execve",           (void *)execve);
    Sforeign_symbol("sigaction",        (void *)sigaction);
    Sforeign_symbol("sigemptyset",      (void *)sigemptyset);
    Sforeign_symbol("sigfillset",       (void *)sigfillset);
    Sforeign_symbol("sigaddset",        (void *)sigaddset);
    Sforeign_symbol("nanosleep",        (void *)nanosleep);
    Sforeign_symbol("clock_gettime",    (void *)clock_gettime);

    /* Threading (std actor) */
    Sforeign_symbol("pthread_create",   (void *)pthread_create);
    Sforeign_symbol("pthread_join",     (void *)pthread_join);
    Sforeign_symbol("pthread_detach",   (void *)pthread_detach);
    Sforeign_symbol("pthread_self",     (void *)pthread_self);
    Sforeign_symbol("pthread_mutex_init",   (void *)pthread_mutex_init);
    Sforeign_symbol("pthread_mutex_lock",   (void *)pthread_mutex_lock);
    Sforeign_symbol("pthread_mutex_unlock", (void *)pthread_mutex_unlock);
    Sforeign_symbol("pthread_mutex_destroy",(void *)pthread_mutex_destroy);
    Sforeign_symbol("pthread_cond_init",    (void *)pthread_cond_init);
    Sforeign_symbol("pthread_cond_wait",    (void *)pthread_cond_wait);
    Sforeign_symbol("pthread_cond_signal",  (void *)pthread_cond_signal);
    Sforeign_symbol("pthread_cond_broadcast",(void*)pthread_cond_broadcast);
    Sforeign_symbol("pthread_cond_destroy", (void *)pthread_cond_destroy);

    /* Memory */
    Sforeign_symbol("malloc",           (void *)malloc);
    Sforeign_symbol("free",             (void *)free);
    Sforeign_symbol("realloc",          (void *)realloc);
    Sforeign_symbol("memcpy",           (void *)memcpy);
    Sforeign_symbol("memmove",          (void *)memmove);
    Sforeign_symbol("memset",           (void *)memset);
    Sforeign_symbol("mmap",             (void *)mmap);
    Sforeign_symbol("munmap",           (void *)munmap);

    /* Errno (std net tcp-raw uses __errno_location on Linux) */
    Sforeign_symbol("__errno_location", (void *)__errno_location);
}

/* ── main ─────────────────────────────────────────────────────────────────── */
/*
 * Write embedded .so to a mkstemp file so Sscheme_program can load it.
 * memfd_create is ideal but requires Linux 3.17+ — use mkstemp for
 * broader compatibility.
 */
static const char *write_program_tmpfile(void) {
    static char path[] = "/tmp/jerboa-prog-XXXXXX";
    int fd = mkstemp(path);
    if (fd < 0) { perror("mkstemp"); exit(1); }
    ssize_t n = write(fd, program_boot_data, program_boot_size);
    if (n != (ssize_t)program_boot_size) { perror("write"); close(fd); unlink(path); exit(1); }
    close(fd);
    return path;
}

int main(int argc, const char *argv[]) {
    /* Signal stdlib modules to skip (load-shared-object ...) calls */
    putenv("JERBOA_STATIC=1");
    Sscheme_init(NULL);
    Sregister_boot_file_bytes("petite", (void *)petite_boot_data, petite_boot_size);
    Sregister_boot_file_bytes("scheme", (void *)scheme_boot_data, scheme_boot_size);
    Sbuild_heap(NULL, custom_init);

    const char *prog_path = write_program_tmpfile();
    Sscheme_program(prog_path, argc, argv);
    unlink(prog_path);

    Sscheme_deinit();
    return 0;
}
CMAIN

echo ""

# ── Step 4: Compile + link static binary ─────────────────────────────────────
echo "==> Step 4: Link static binary → ${OUTPUT}"

# Locate any extra static archives the musl Chez install provides
LZ4_A="${CSV_DIR}/liblz4.a"
Z_A="${CSV_DIR}/libz.a"
EXTRA_ARCHIVES=""
[ -f "${LZ4_A}" ] && EXTRA_ARCHIVES="${EXTRA_ARCHIVES} ${LZ4_A}"
[ -f "${Z_A}"   ] && EXTRA_ARCHIVES="${EXTRA_ARCHIVES} ${Z_A}"

musl-gcc \
    -I"${CSV_DIR}" \
    -O2 \
    -o "${OUTPUT}" \
    "${OUTPUT}-main.c" \
    "${CSV_DIR}/libkernel.a" \
    ${EXTRA_ARCHIVES} \
    "${NATIVE_A}" \
    -lm -lpthread \
    -static

# ── Step 5: Strip + verify ────────────────────────────────────────────────────
echo ""
echo "==> Step 5: Strip and verify"
strip "${OUTPUT}"

SIZE=$(du -sh "${OUTPUT}" | cut -f1)
echo ""
echo "=== Build complete ==="
echo "    ${OUTPUT}: ${SIZE}"
file "${OUTPUT}"
echo ""

# Warn if over target
SIZE_BYTES=$(stat -c%s "${OUTPUT}")
if [ "${SIZE_BYTES}" -gt $((25 * 1024 * 1024)) ]; then
    echo "WARNING: binary is ${SIZE} — exceeds 25MB target"
fi

# ── Cleanup intermediates ─────────────────────────────────────────────────────
rm -f "${WPO_SO}" petite_boot.h scheme_boot.h program_boot.h "${OUTPUT}-main.c"
rm -rf "${OBJ_DIR}"
