#!/bin/sh
# build-binary.sh — Build a self-contained Jerboa binary.
#
# Usage:
#   support/build-binary.sh <entry.ss> <output-name>
#
# Portable across FreeBSD, Linux, and macOS — uses the system Chez install
# (libkernel.a + petite.boot + scheme.boot) discovered by globbing standard
# prefixes for csv*/<machine-type>/.
#
# Output: ./<output-name>  (a real ELF/Mach-O binary that runs Jerboa)

set -eu

if [ $# -lt 2 ]; then
    echo "Usage: $0 <entry.ss> <output-name>" >&2
    exit 1
fi

SCRIPT="$1"
OUTPUT="$2"

JERBOA_HOME="${JERBOA_HOME:-$(cd "$(dirname "$0")/.." && pwd)}"
SCHEME="${SCHEME:-scheme}"
LIBDIRS="${JERBOA_HOME}/lib"

# ── Detect OS and pick compiler + base link flags ────────────────────────────
OS=$(uname -s)
case "$OS" in
    FreeBSD)
        CC_DEFAULT=cc
        OS_LIBS="-lm -lpthread -lncurses -L/usr/local/lib -liconv"
        ;;
    Darwin)
        CC_DEFAULT=cc
        OS_LIBS="-lm -lpthread -lncurses -liconv"
        ;;
    Linux)
        CC_DEFAULT=gcc
        # Try both -lncurses and -ltinfo; -ltinfo is split out on some distros.
        if [ -f /usr/lib/x86_64-linux-gnu/libtinfo.so ] || [ -f /usr/lib64/libtinfo.so ]; then
            OS_LIBS="-lm -ldl -lpthread -ltinfo"
        else
            OS_LIBS="-lm -ldl -lpthread -lncurses"
        fi
        ;;
    *)
        CC_DEFAULT=cc
        OS_LIBS="-lm -lpthread -lncurses"
        ;;
esac
CC="${CC:-$CC_DEFAULT}"

# ── Find the Chez install dir (libkernel.a + scheme.h + boot files) ──────────
MACHINE_TYPE=$("$SCHEME" -q <<'EOF'
(display (machine-type)) (exit)
EOF
)

CSV_DIR=""
for prefix in /usr/local/lib /usr/lib /usr/lib64 /opt/homebrew/lib /opt/local/lib; do
    for d in "$prefix"/csv*/"$MACHINE_TYPE"; do
        if [ -f "$d/libkernel.a" ] && [ -f "$d/scheme.h" ] && [ -f "$d/petite.boot" ]; then
            CSV_DIR="$d"
            break 2
        fi
    done
done

if [ -z "$CSV_DIR" ]; then
    echo "ERROR: cannot find Chez install for machine-type '$MACHINE_TYPE'." >&2
    echo "       Searched csv*/$MACHINE_TYPE under:" >&2
    echo "         /usr/local/lib /usr/lib /usr/lib64 /opt/homebrew/lib /opt/local/lib" >&2
    exit 1
fi

echo "=== Jerboa binary build: $SCRIPT -> $OUTPUT ==="
echo "    OS:    $OS"
echo "    CC:    $CC"
echo "    Chez:  $CSV_DIR"
echo ""

# ── Step 1: WPO-compile entry script -> program.so ───────────────────────────
WPO_SO="${OUTPUT}.wp.so"
OBJ_DIR=$(mktemp -d "/tmp/jerboa-bin-obj.XXXXXX")
trap 'rm -rf "$OBJ_DIR" "$WPO_SO" petite_boot.h scheme_boot.h program_boot.h "${OUTPUT}-main.c"' EXIT

echo "==> [1/4] WPO compile"
"$SCHEME" --libdirs "$LIBDIRS" \
    --script "$JERBOA_HOME/support/build-boot.ss" "$SCRIPT" "$WPO_SO" "$OBJ_DIR"
echo ""

# ── Step 2: Embed boot files + program as C byte arrays ──────────────────────
echo "==> [2/4] Embedding boot files as C arrays"

embed() {
    in="$1"; stem="$2"
    var="${stem}_data"; sz="${stem}_size"; out="$stem.h"
    printf 'static const unsigned char %s[] = {\n' "$var" > "$out"
    # macOS `od` emits a trailing blank line; drop it before the substitution
    # so we don't generate a stray "0x," at the end.
    od -An -tx1 -v "$in" \
        | sed -e '/^[[:space:]]*$/d' \
              -e 's/^ *//;s/ *$//;s/  */ /g;s/ /,0x/g;s/^/0x/;s/$/,/' >> "$out"
    printf '};\nstatic const unsigned int %s = sizeof(%s);\n' "$sz" "$var" >> "$out"
}

embed "$CSV_DIR/petite.boot"  petite_boot
embed "$CSV_DIR/scheme.boot"  scheme_boot
embed "$WPO_SO"               program_boot
echo ""

# ── Step 3: Generate main.c ──────────────────────────────────────────────────
echo "==> [3/4] Generate ${OUTPUT}-main.c"

cat > "${OUTPUT}-main.c" <<'CMAIN'
/* Jerboa binary entry point — generated by support/build-binary.sh */
#include "scheme.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>

#include "petite_boot.h"
#include "scheme_boot.h"
#include "program_boot.h"

static const char *write_program_tmpfile(void) {
    static char path[] = "/tmp/jerboa-prog-XXXXXX";
    int fd = mkstemp(path);
    if (fd < 0) { perror("mkstemp"); exit(1); }
    ssize_t n = write(fd, program_boot_data, program_boot_size);
    if (n != (ssize_t)program_boot_size) {
        perror("write"); close(fd); unlink(path); exit(1);
    }
    close(fd);
    return path;
}

int main(int argc, const char *argv[]) {
    Sscheme_init(NULL);
    Sregister_boot_file_bytes("petite",
        (void *)petite_boot_data, petite_boot_size);
    Sregister_boot_file_bytes("scheme",
        (void *)scheme_boot_data, scheme_boot_size);
    Sbuild_heap(NULL, NULL);

    const char *prog_path = write_program_tmpfile();
    Sscheme_program(prog_path, argc, argv);
    unlink(prog_path);

    Sscheme_deinit();
    return 0;
}
CMAIN
echo ""

# ── Step 4: Compile + link ───────────────────────────────────────────────────
echo "==> [4/4] Compile + link -> $OUTPUT"

EXTRA_ARCHIVES=""
for a in liblz4.a libz.a; do
    if [ -f "$CSV_DIR/$a" ]; then
        EXTRA_ARCHIVES="$EXTRA_ARCHIVES $CSV_DIR/$a"
    fi
done

# shellcheck disable=SC2086
$CC -I"$CSV_DIR" -O2 \
    -o "$OUTPUT" \
    "${OUTPUT}-main.c" \
    "$CSV_DIR/libkernel.a" \
    $EXTRA_ARCHIVES \
    $OS_LIBS

echo ""
echo "=== Build complete ==="
ls -lh "$OUTPUT"
file "$OUTPUT" 2>/dev/null || true
